/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/obj.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Node1.geometry} material={materials.x1} />
      <mesh castShadow receiveShadow geometry={nodes.Node2.geometry} material={materials.x1} />
      <mesh castShadow receiveShadow geometry={nodes.Node3.geometry} material={materials.x1} />
      <mesh castShadow receiveShadow geometry={nodes.Node4.geometry} material={materials.x1} />
      <mesh castShadow receiveShadow geometry={nodes.Node5.geometry} material={materials.x1} />
    </group>
  )
}

useGLTF.preload('/obj.glb')
